modLoader="javafml"
loaderVersion="[39,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues"
logoFile="logo.png"

[[mods]]
modId="botania"
version="${file.jarVersion}"
displayName="Botania"
displayURL="https://botaniamod.net"
description="Botania is a mod that adds nature magic to Minecraft."
authors="Vazkii, wiiv, williewillus, dylan4ever, Hubry, Alwinfy, artemisSystem, Falkory220"
credits="Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw, quat1024, ToMe25, Eutro and others"

itemIcon="botania:cosmetic_botanist_emblem" # custom icon for Catalogue's mod list
configBackground="botania:textures/block/livingrock_bricks.png" # background for Configured's generated config screen

[[dependencies.botania]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.65,)"

[[dependencies.botania]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19.2-76,)"

[[dependencies.botania]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"

[[dependencies.botania]]
    modId="gardenofglass"
    mandatory=false
    versionRange="[1.11,)"

[[dependencies.botania]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[9.1.116,)"

[[dependencies.botania]]
    modId="ears"
    mandatory=false
    versionRange="[1.4.5,)"
