modLoader="javafml"
loaderVersion="[36,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues"
logoFile="logo.png"

[[mods]]
modId="botania"
version="${file.jarVersion}"
displayName="Botania"
displayURL="https://botaniamod.net"
description="Botania is a mod that adds nature magic to Minecraft."
authors="Vazkii, wiiv, williewillus, dylan4ever, Hubry"
credits="Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw, quat1024, ToMe25, Alwinfy, Eutro and others"

[[dependencies.botania]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.42,)"

[[dependencies.botania]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-48,)"

[[dependencies.botania]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.4-4.0.3.5,)"

[[dependencies.botania]]
    modId="gardenofglass"
    mandatory=false
    versionRange="[1.7,)"
