modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues" #optional
displayURL="https://botaniamod.net" #optional
logoFile="logo.png" #optional
credits="Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw" #optional
authors="Vazkii, wiiv, williewillus, dylan4ever" #optional

[[mods]]
modId="botania"
version="${file.jarVersion}"
displayName="Botania"
description='''
Botania is a mod that adds nature magic to Minecraft'''

[[dependencies.botania]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.7,)"

[[dependencies.botania]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-48,)"

[[dependencies.botania]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.4-4.0.3.0,)"

[[dependencies.botania]]
    modId="gardenofglass"
    mandatory=false
    versionRange="[1.6,)"
