modLoader="javafml"
loaderVersion="[36,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues"
logoFile="logo_gog.png"

[[mods]]
modId="gardenofglass"
version="${file.jarVersion}"
displayName="Garden of Glass"
displayURL="https://botaniamod.net/gardenofglass.php"
description="An extension to Botania that adds skyblock like gameplay."
authors="Vazkii, wiiv, williewillus, Hubry"

[[dependencies.gardenofglass]]
    modId="botania"
    versionRange="[1.16.4-413,)"
    mandatory=true
    ordering="AFTER"
