modLoader="javafml" #mandatory
loaderVersion="[33,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues" #optional
displayURL="https://botaniamod.net" #optional
logoFile="logo_gog.png" #optional
credits="" #optional
authors="Vazkii, wiiv, williewillus" #optional

[[mods]]
modId="gardenofglass"
version="${file.jarVersion}"
displayName="Garden of Glass"
description='''
An extension to Botania that adds skyblock like gameplay.'''

[[dependencies.gardenofglass]]
    modId="botania"
    versionRange="[1.16.2-405,)"
    mandatory=true
    ordering="AFTER"
    side="BOTH"
